import Head from 'next/head';

import JobseekLayout from '@/layouts/JobseekLayout';
import AdvancedSearch from '@/modules/AdvancedSearch';

export default function AdvancedSearchPage() {
  return (
    <>
      <Head>
        <title>Advanced search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <JobseekLayout>
          <AdvancedSearch />
        </JobseekLayout>
      </main>
    </>
  );
}
