import Head from 'next/head';

import JobseekLayout from '@/layouts/JobseekLayout';
import AccountManager from '@/modules/AccountManager';
import Breadcrumbs from '@/components/Breadcrumbs';

export default function AccountManagerPage() {
  return (
    <>
      <Head>
        <title>Account Manager Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <JobseekLayout>
          <Breadcrumbs />
          <AccountManager />
        </JobseekLayout>
      </main>
    </>
  );
}