import Head from 'next/head';

import EmployerSignIn from '@/modules/EmployerSignIn';
import EmployerHeader from '@/components/EmployerHeader';
import Footer from '@/components/Footer';

export default function EmployerSignInPage() {
  return (
    <>
      <Head>
        <title>Employer SignIn Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <EmployerHeader type="sign-in" />
        <EmployerSignIn />
        <Footer />
      </main>
    </>
  );
}
