import Head from 'next/head';

import HomePage from '@/modules/HomePage';
import EmployerHeader from '@/components/EmployerHeader';
import Breadcrumbs from '@/components/Breadcrumbs';
import Footer from '@/components/Footer';
import JobPostedComponent from '@/modules/JobPosted';

export default function JobPosted() {
  return (
    <>
      <Head>
        <title>Job Posted Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <EmployerHeader />
        <Breadcrumbs />
        <JobPostedComponent />
        <Footer />
      </main>
    </>
  );
}