import Head from 'next/head';

import JobseekLayout from '@/layouts/JobseekLayout';
import AccountManager from '@/modules/AccountManager';
import Breadcrumbs from '@/components/Breadcrumbs';
import Plan from '@/modules/Plan';

export default function PlanPage() {
  return (
    <>
      <Head>
        <title>Plan Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <JobseekLayout>
          <Breadcrumbs />
          <Plan />
        </JobseekLayout>
      </main>
    </>
  );
}